apiVersion: v1
kind: Pod
metadata:
  name: bad-no-resources-pod
  namespace: policy-demo
spec:
  containers:
    - name: bad
      image: ghcr.io/yuvalpinto/secubernetes-demo:latest
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        privileged: false
